language: node_js
node_js:
- '11'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: wAUU+/xTm1OW/ZC17KhZzOgWPWACPAgaW3psguZqNo11wN76f2oRT83VFseLgKcfJyO04UFdd23HP16or+gBMO6hYqmmjYxHo9thxCAoJjW9e2GSHoSXvC/mWefT5lnvc+qbesMFk0U1EXox8JK0dD2LHd561PC0iaV1jr/FR4sSPvORyLb8pjwSj/bfFpiySjqRgOZcUoLjWCoId4XsQomN1AA4Ktbqxj0Wv/Ve6JUzjvHlG/Uy8C1bVjb+Dr8M14zVcHlxlqsMyhDdtqbQrzzEopx09+sDBNfyzkM59zHwD/q0oB8T7rrgK+SSOt7f/Of2i5vpJX/iISCarhj4WeqovUFwV+i2wEvtHocjirIArEY9cALdQppGxI+wnGThwuBK8LJFtaAvUlfAlObGW3eTy0wmvbjfUNKgYT4f6w/g9ne9crbjABcnaaa6dg/+JFLw/8vbnrCXQCPPbpstq08ZVCc36CNnYsmaVinYx1M0v1MQgc3TSxSRbaUwhmDFNHtmkTpLgPigS26QG17stU0MA6MAAdqwN0BQD8vg0byUS/8fU2PFjo4RUfw+iEmiMdoIGdy+smz7LSZoUCBBQdslieOMmRiF7KhMekAHVA1mzKfGnv1os/oe/pIbJeTvO6OqIVNqWSnOspW5MktNCw0DletvuFzUSS4iKN/Tpu4=
  on:
    tags: true
    repo: RadonApp/radon-extension-plugin-youtubemusic
