language: node_js
node_js:
- '7'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: neapp-ci@me.dgardiner.net
  api_key:
    secure: g+D7VnOrLAakL0MFKrGUuRlN6S8FiXErXNLxlmi0nVg2hALQBqSIDW1hvh52CcNYhUEOl7raS6Z9xBI2cgs1hkjN2k9ILZk0cbUqZBgZ8nfNyzLy47oaGZJ1kk9/MKyLA3GtV6GSSNxEm41gchS1qurmJVuv9oyaHdh8SF+yzMrQH/hE27jfaWYOTPQ6nztdHs5iFQZkBt02/GDsIwcY548ZtRivtYfRch7ibbjERe9UgPWoMBk3IEljvKvk+ahlNVS1/Ab7JdJEx79eTxQEJeKDMHDCidPrnoj0KvaYHi19trFqja2cqH2v4dXaFRLXWPfA7BMQb1zQIQWDfc6tFiHzh7l/vTPdY2548Ulik19jxTGkJfeOlrJJ3SFP/FsbYYk2FOINKQT0Vr6/vDl/7sZLPgP3IadflKcNslFBhm88+72zrk1wRQmVfX9q5Weh4AoSUV3xNb1WhD01lJsAN8R8rFz7avfIt8P8aeIk51a8YhKA/bu32cYom2K9QE6tiTSrLpbKX9FdYbMvaMPHoPe9SvSZhJNMzruZw4C3grIQE2DfqT2lV5QX5fRJIctq+CfBYZMjZNjukz/1nNO4rvcp8wmVfqc+r8UP0r26qNkI3cmCtJPFa8swvjPNM5AyHrovqmD3HP6RPxdUDU2yXh32bKSE8SxRucJ9LV1BUYM=
  on:
    repo: RadonApp/radon-extension-plugin-youtubemusic
    tags: true
